- README.md
re-order sections to mention things like how to
use the sdk sooner, things like how to update
proto files later.
early on, say to use pod 'TokenSdk', '~> 1.0.72'
which works with sandbox. Only after that mention
how to use scary new versions
> readme changes for non-token developers:

- Samples/TKSwift/TKSwift/ViewController.swift
- src/api/TokenIO.h
- src/api/TokenIO.m
- src/api/TokenIOSync.m
createMember, loginMember had parameter typo "onSucess"
with this change, each method has two signatures: one with typo remaining, one with typo fixed
> typo fix "onSucess"

- bin/publish
- src/rpc/TKRpc.m
- src/util/TKUtil.h
- src/util/TKUtil.m
CFBundleShortVersionString is not a safe option to get version number. The malfunction happen while Objc project add TokenSDK as a pod.
> Sl.version

- src/rpc/TKRpcSyncCall.m
- tests/TKSetupSamples.m
for whom is interested in the sync call bug, the reason is the the main thread has been hung by the semaphore. In the meanwhile, the gprc calls are trying to back to main thread for OnSuccess calls.
To fix this, I add runloop check here to allow other main thread calls can "jump the queue" before semaphore is done.
> fix runloop problem in sync calls

- sample/TKSetupSamples.m
- src/api/TKMember.h
- src/api/TKMember.m
- src/api/TKMemberSync.h
- src/api/TKMemberSync.m
- src/api/TKTypedef.h
- src/rpc/TKClient.h
- src/rpc/TKClient.m
- tests/TKAccountsTests.m
- tests/TKTestBase.h
- tests/TKTestBase.m
- tests/TKTransferTokenRedemptionTests.m
This is similar to https://github.com/tokenio/sdk-objc/pull/37 , which had a bug + I reverted.
This change, unlike that change, doesn't remove _bank from TKTestBase, which I learned is the variable behind the property "bank".
> port Member.createTestBankAccount to objc (again)

- src/rpc/TKRpcSyncCall.m
OnSuccess and OnError will always be invoked on main thread, you are correct.
So I change my fix only for mainThread. if the sync calls are invoked in some other thread, it will just wait for the semaphore as before.
> only invoke runloop on main thread

- sample/TKAccessSamples.m
this test wasn't waiting for an async to finish before
using its "return value."
and it wasn't waiting at the end, either.
so if you ran the test in isolation, it passed,
but if you ran it as part of a suite, later on
it would async'ly throw an exception
fixed those.
split this long test into two smaller tests so
I don't have to think so hard to figure out what's
going on.
> fix test, un-comment it

- sample/TKAccessSamples.m
one of these tests failed once: it endorsed a token, then "found"
that token again with getAccessTokens; it compared these two copies
of the token by equality. This mostly passed, but it failed just now:
the two token protos had a couple of signatures in a different order.
Semantically, these tokens are "the same", but proto isEqual: check
didn't like it.
So change that test to check for equal .id_p instead of the whole structure.
And change some other checks, too. Just because they've been passing
so far doesn't mean they won't go flaky later.
> fix flaky test

- src/api/AccessTokenConfig.h
- src/api/AccessTokenConfig.m
https://developer.token.io/sdk/objcdoc/Classes/AccessTokenConfig.html looks unusual. before it shows the usual web-like docs, there's a section that shows lots of comments
```
/**
* Creates a new instance with a provided redeemer alias (the 'payload.to' field).
*
* @param redeemerAlias alias of the token redeemer
*/
```
When I looked at the header file, I noticed something unusual: the instance variables were in the header file; we usually put them in the `.m` file. I tried moving them to the the `.m` file and the docs looked more like usual. And the tests still pass.
> AccessTokenConfig.* : make jazzy doc look less weird

- sample/TKAccessSamples.m
- sample/TKSampleBase.h
- sample/TKSampleBase.m
Data backing getAccessTokens is update asynchronously so we need to poll.
Use the sync api to avoid concurrency issues while polling.
> Fix getAccessToken sample

- tests/TKErrorHandlerTests.m
Once dev-key becomes required this test will throw the wrong error.
> Add dev-key header to ErrorHandlerTests

- src/api/PagedArray.h
- src/api/TKAccount.h
- src/api/TKAccountSync.h
- src/api/TKBalance.h
- src/api/TKMember.h
- src/api/TKMemberSync.h
- src/api/TokenIOBuilder.h
- src/api/TokenIOSync.h
- src/api/TransferTokenBuilder.h
Jazzy generates our web docs. When it sees a comment-less property, it just says "undocumented"; it doesn't say the type of the property, which would be pretty useful. Grr.
So add comments for properties of things in src/api. You wouldn't think a comment like "Member's ID" for a TKMember property named `id` would be useful, but Jazzy likes them.
> comments for "jazzy" tool

- sample/TKAccessSamples.m
don't just use allAccounts ; if you see "allAccounts" but not, e.g., "allBalances", it's easy to to think allAccounts means "everything about all accounts"
Old sample was useToken , getAccounts, (do nothing with them), clearToken. Change to show using the accounts before clearToken.
in replace examples, don't replace one access with unrelated access.
> access sample more obvious

- src/api/TokenIO.h
- src/api/TokenIO.m
- src/api/TokenIOBuilder.h
- src/api/TokenIOBuilder.m
- tests/TokenIOTests.m
if user sets custom certs path in token io builder, token io will create grpc channel with the given certs instead.
use in netcraft pan testing.
> add certspath in tokeniobuilder

- src/rpc/TKClient.m
When I look at the gateway change https://github.com/tokenio/gateway/commit/0f57e81f12740ee5052db40634d950510e87d9a0 , I ?think? it means we want this change in sdk-objc.
> getTransfers: use filter.tokenId instead of tokenId, it's newer

- sample/TKAccessSamples.m
- tests/TKTransactionsTests.m
so far, our redeem-access-token sample code shows how to use a token that has allAccounts. But if the token-grantor replaces that allAccounts with something more specific, e.g., edits the permissions in our iPhone app, that sample code fails to fetch any data. This new sample code shows how to use allAccounts if granted else use more-specific permissions.
bonus: fix old replace-access sample mistake: it was trying to set new config by calling methods on old config
bonus: fix a test that was comparing a pointer to string "10" being above 0, rather than converting that "10" to an int. it worked in that context, but was confusing.
> sample code += use access token that maybe does not have allAccounts

- bin/gen-doc
full-featured jazzy makes a spare "docsets" copy
of the docs plus a tarball. Handy, but not in
our context of building docs for our website and
wondering "what is this tarball doing here?".
So ask jazzy to make that "docsets" far far away.
> jazzy doc tool, omit "docsets" cruft, please

- TokenSdk.podspec
- sample/TKSetupSamples.m
- src/api/TKMemberRecoveryManager.h
- src/api/TKMemberRecoveryManager.m
- src/api/TokenIO.h
- src/api/TokenIO.m
- src/api/TokenIOBuilder.h
- src/api/TokenIOBuilder.m
- src/api/TokenIOSync.h
- src/api/TokenIOSync.m
- src/security/secureenclave/TKSecureEnclaveCryptoEngine.h
- src/security/secureenclave/TKSecureEnclaveCryptoEngine.m
- src/security/secureenclave/TKSecureEnclaveCryptoEngineFactory.h
- src/security/secureenclave/TKSecureEnclaveCryptoEngineFactory.m
- src/security/token/TKTokenCryptoEngineFactory.h
- tests/TKTestBase.m
We need to support Secure Enclave + Passcode only in some case to pass Apple's review guideline.
In the new design, devs will need to set crypto engine factory instead of key store when they create a TokenIO. So that the devs can have broader options in customizing a crypto engine instead of only the key store.
> add crypto engine to TokenIOBuilder

- src/api/TKAccount.m
- src/api/TokenIO.m
- src/api/TokenSdk.h
- src/rpc/TKRpc.m
- src/rpc/TKUnauthenticatedClient.m
- src/security/TKCrypto.h
- src/security/TKCryptoEngine.h
- tests/TKMemberRegistrationTests.m
tell TokenSdk.h to import TKCryptoEngineFactory.h so jazzy
doc tool "sees" it.
that broke the build, so some other #import changes to un-break
> import fun: TokenSdk += TKTokenCryptoEngineFactory and followup

- tests/TKTransferTokenRedemptionTests.m
We're deprecating bank authorization payments. Removed a similar test in java tests here https://github.com/tokenio/sdk-java-tests/pull/134.
> remove bank authorization payment test

- TokenSdk.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- bin/run-tests
- bin/run-tests-local
- bin/run-tests-sandbox
- bin/run-tests-stg
After update to Xcodebuild version 10E1001, it can not handle the disabled tests correctly in the build schema. Explicitly set it in build script can bypass the problem.
IDEWorkspaceChecks.plist is a file generated by new version Xcode and is suggested to persist in source control by Apple.
> add skip tests options in xcodebuild
